- id: flake8-intsights
  name: flake8-intsights
  description: "Uncompromising and opinionated flake8 plugin which follows Intsights' practices"
  entry: flake8
  language: python
  language_version: python3
  require_serial: true
  types: [python]
