blank_lines_test_text_001 = ''
blank_lines_test_text_002 = '\n'
blank_lines_test_text_003 = '\n\n'
blank_lines_test_text_004 = 'pass'
blank_lines_test_text_005 = 'pass\n'
blank_lines_test_text_006 = 'pass\n\n'
blank_lines_test_text_007 = '\npass\n'
blank_lines_test_text_008 = '\n\npass\n'
